### ISSUE TITLE
github repo in elm-package.json

### ISSUE THREAD

**Issue by berndca** [Gizra/generator-elmlang#20]
I noticed the initial dialog asking for the github repo url. It appears that this info does not make it into elm-package.json. I still get 

  Message:
      Error reading file elm-package.json:
      Problem with the `repository` field.

  Upper case characters are not allowed in package names.

and find the old defaults there. I assume that this was not your intention and figured I let you know.

Thanks, Bernd

**Comment by amitaibu** [comment]
Indeed, nice catch. Care to try a PR? :)

**Comment by berndca** [comment]
I'd love to contribute, however I know nothing about yeoman generators and have never done any node related work. Please let me know of there is anything like QA or documentation related tasks I could help with.

Thanks, Bernd

**Comment by amitaibu** [comment]
Ok, closing in favor of #22

**Comment by amitaibu** [comment]
Published a new version, so check it out :)

**Comment by berndca** [comment]
Thanks, the repo field is filled in now.
