### ISSUE TITLE
elm-package.json uses outdated elm 0.15.1 dependencies.

### ISSUE THREAD

**Issue by berndca** [Gizra/generator-elmlang#21]
Please update the elm-package.json template to support elm 0.16.

I have included my version below.

Thanks, Bernd

    "dependencies": {
        "deadfoxygrandpa/elm-test": "2.0.0 <= v < 3.0.0",
        "elm-lang/core": "3.0.0 <= v < 4.0.0",
        "evancz/elm-effects": "2.0.1 <= v < 3.0.0",
        "evancz/elm-html": "4.0.2 <= v < 5.0.0",
        "evancz/elm-http": "3.0.0 <= v < 4.0.0",
        "evancz/start-app": "2.0.2 <= v < 3.0.0"
    },
    "elm-version": "0.16.0 <= v < 0.17.0"

**Comment by amitaibu** [comment]
Let's close this in favor of https://github.com/Gizra/generator-elmlang/pull/17 (which is blocked by the testing lib)
