### ISSUE TITLE
How do you include dependencies like Bootstrap?

### ISSUE THREAD

**Issue by wjdhamilton** [Gizra/generator-elmlang#28]
I'm sure this is just because I'm not at all experienced with Yeoman, but I cannot work out how to include dependencies such as bootstrap. In fact, I can't see any evidence that styles.scss is incorporated into the generated app at all. I can see the styles and bower tasks are run by gulp and the output is definitely present in the build folders but there is no sign of them in the compiled elm app. I can include them manually by editing index.html, however I assumed the generator would handle these things automatically...

Any thoughts?

**Comment by amitaibu** [comment]
Ha, seems I forgot to add the link to the css. Care to create a PR to add something like [this](https://github.com/Gizra/elm-spa-example/blob/master/src/index.html#L9)?

As for adding bootstrap via bower (as opposed to adding a harcoded link to the CDN), we should probably add a bower task to gulp. Would be great if you could give it a try 😉

**Comment by wjdhamilton** [comment]
1. I'll do that right now. Should be easy enough since I've done it already in my own app!
2. I'll have a look at this, but this is all new to me so please don't expect it very soon. I'll create a separate issue for it too so it's separate.

**Comment by amitaibu** [comment]
👍
