### ISSUE TITLE
How do i run it ?

### ISSUE THREAD

**Issue by ramstein74** [Gizra/generator-elmlang#34]
Hello i did yo elmlang and then i dont know how to start my project

i did 
gulp
 and got this 
![image](https://cloud.githubusercontent.com/assets/1210858/18870533/efb22a78-84a8-11e6-9ab1-de486d205618.png)

thank you

**Comment by wjdhamilton** [comment]
You need to edit your elm-package.json and populate the repository field with a value such as `your-github-account/app_repository`. It's an elm requirement that does not please everyone, but you don't actually need to use a real repository.

**Comment by DavidHernandez** [comment]
When you use Yeoman to generate a new project it asks you a couple questions. One of them is the github repository of the project. After that, gulp should run correctly. If you don't want to generate a new project, you can do the change propossed on the previous comment.
