### ISSUE TITLE
Add Config to have unique config per env

### ISSUE THREAD

**Issue by amitaibu** [Gizra/generator-elmlang#37]
Something like [this](https://github.com/Gizra/elm-hedley/blob/45eb8517abb5d89f18937fcf32c9f38aebe6b733/src/elm/Config.elm) which we done resolve [here](https://github.com/Gizra/elm-hedley/blob/2a28e1abd907cca93ab3f843f19ed31cc5e85e97/src/elm/Config/Update.elm#L35)

**Comment by DavidHernandez** [comment]
@amitaibu isn't this issue already resolved?
